services:
  - type: web
    name: studymate-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn studymate.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: django-insecure-&#=h&oa&*wyz)m#finccr@vh=0b5ofy_$zs*#xsh3hmh394^5x
      - key: MONGODB_URI
        value: mongodb://localhost:27017/studymate  # use Atlas URI for production
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: studymate-backend.onrender.com
